// //--------------------------------------------------------
// //   This is the setup file for the database. I include 
// //   it here as a bit of documentation. This file has 
// //   already run. THIS FILE SHOULD NOT BE RUN AGAIN!!!
// //   THIS FILE HAS ALREADY BEEN RAN, DO NOT RUN AGAIN!!
// //---------------------------------------------------------
// const sqlite3 = require('sqlite3').verbose();
// const db = new sqlite3.Database('db/storyworkshop.db');

// const occupations_var = [
//     "Accountant",
//     "Actor/Actress",
//     "Architect",
//     "Baker",
//     "Barber/Hairdresser",
//     "Biologist",
//     "Carpenter",
//     "Chef",
//     "Chemist",
//     "Civil Engineer",
//     "Clergy",
//     "Computer Programmer",
//     "Construction Worker",
//     "Counselor",
//     "Dancer",
//     "Dentist",
//     "Detective",
//     "Doctor",
//     "Economist",
//     "Electrician",
//     "Farmer",
//     "Fashion Designer",
//     "Firefighter",
//     "Fisherman",
//     "Florist",
//     "Graphic Designer",
//     "Historian",
//     "Interior Designer",
//     "Journalist",
//     "Judge",
//     "Lawyer",
//     "Librarian",
//     "Lifeguard",
//     "Mail Carrier",
//     "Marketing Manager",
//     "Mechanic",
//     "Musician",
//     "Nurse",
//     "Occupational Therapist",
//     "Optometrist",
//     "Paramedic",
//     "Pharmacist",
//     "Photographer",
//     "Physicist",
//     "Pilot",
//     "Police Officer",
//     "Politician",
//     "Professor",
//     "Psychologist",
//     "Real Estate Agent",
//     "Receptionist",
//     "Research Scientist",
//     "Salesperson",
//     "Social Worker",
//     "Software Developer",
//     "Surgeon",
//     "Teacher",
//     "Technical Writer",
//     "Translator",
//     "Veterinarian",
//     "Waiter/Waitress",
//     "Web Developer",
//     "Zoologist",
//     "Actor",
//     "Aeronautical Engineer",
//     "Aerospace Engineer",
//     "Agronomist",
//     "Air Traffic Controller",
//     "Animal Trainer",
//     "Anthropologist",
//     "Archaeologist",
//     "Art Director",
//     "Astronaut",
//     "Astronomer",
//     "Auctioneer",
//     "Baker",
//     "Bank Teller",
//     "Barista",
//     "Bartender",
//     "Beekeeper",
//     "Biochemist",
//     "Botanist",
//     "Bricklayer",
//     "Building Inspector",
//     "Butcher",
//     "Butler",
//     "Calligrapher",
//     "Cameraman",
//     "Cardiologist",
//     "Cartographer",
//     "Cartoonist",
//     "Chaplain",
//     "Chemist",
//     "Choreographer",
//     "Cinematographer",
//     "Coach",
//     "Composer",
//     "Copywriter",
//     "Costume Designer",
//     "Criminal Investigator"
// ];

// const goodHabits_var = [
//   "Regular exercise",
//   "Punctuality",
//   "Empathy",
//   "Strong work ethic",
//   "Patience",
//   "Creativity",
//   "Consistent communication",
//   "Critical thinking",
//   "Open-mindedness",
//   "Team collaboration",
//   "Gratitude practice",
//   "Healthy eating",
//   "Active listening",
//   "Setting goals",
//   "Time management",
//   "Mindfulness meditation",
//   "Daily journaling",
//   "Kindness towards others",
//   "Staying organized",
//   "Seeking feedback",
//   "Continual learning",
//   "Taking breaks",
//   "Financial planning",
//   "Environmental sustainability",
//   "Volunteering",
//   "Daily reading",
//   "Self-reflection",
//   "Problem-solving",
//   "Resilience",
//   "Positive self-talk",
//   "Healthy boundaries",
//   "Empowering others",
//   "Adaptability",
//   "Self-care practices",
//   "Conservation of resources",
//   "Active participation in community",
//   "Prioritizing tasks",
//   "Self-discipline",
//   "Regular sleep schedule",
//   "Encouraging others",
//   "Practice of forgiveness",
//   "Clear communication",
//   "Mindful eating",
//   "Creative expression",
//   "Daily affirmations",
//   "Physical self-care",
//   "Regular check-ins with loved ones",
//   "Learning a new skill",
//   "Developing healthy routines",
//   "Emotional intelligence",
//   "Seeking opportunities for growth",
//   "Celebrating successes",
//   "Maintaining personal hygiene",
//   "Practicing gratitude",
//   "Respecting others' boundaries",
//   "Setting boundaries",
//   "Reflecting on achievements",
//   "Being proactive",
//   "Supporting others' goals",
//   "Promoting positivity",
//   "Continual self-improvement",
//   "Taking initiative",
//   "Active participation in hobbies",
//   "Regular health check-ups",
//   "Seeking mentorship",
//   "Building positive relationships",
//   "Completing tasks on time",
//   "Respecting diversity",
//   "Being empathetic",
//   "Engaging in meaningful conversations",
//   "Encouraging self-care in others",
//   "Promoting inclusivity",
//   "Practicing self-compassion",
//   "Being environmentally conscious",
//   "Showing appreciation",
//   "Seeking balance in life",
//   "Learning from mistakes",
//   "Fostering a growth mindset",
//   "Encouraging creativity in others",
//   "Being present in the moment",
//   "Maintaining a positive attitude",
//   "Acknowledging achievements",
//   "Setting realistic goals",
//   "Expressing gratitude towards others",
//   "Reflecting on experiences",
//   "Supporting sustainable practices",
//   "Being a good listener",
//   "Promoting harmony in relationships",
//   "Taking ownership of actions",
//   "Cultivating a sense of purpose",
//   "Seeking feedback for personal growth",
//   "Regular exercise of self-discipline",
//   "Promoting teamwork",
//   "Engaging in acts of kindness",
//   "Practicing active empathy",
//   "Prioritizing mental health",
//   "Demonstrating honesty and integrity"
// ];

// const badHabits_var = [
//   "Procrastination",
//   "Impulsiveness",
//   "Tardiness",
//   "Perfectionism",
//   "Overcritical",
//   "Laziness",
//   "Disorganization",
//   "Impatience",
//   "Gossiping",
//   "Indecisiveness",
//   "Nail-biting",
//   "Overeating",
//   "Oversleeping",
//   "Excessive drinking",
//   "Smoking",
//   "Drug abuse",
//   "Biting nails",
//   "Over-spending",
//   "Habitual lying",
//   "Negative self-talk",
//   "Interrupting others",
//   "Being judgmental",
//   "Chronic lateness",
//   "Skipping meals",
//   "Self-doubt",
//   "Making excuses",
//   "Avoiding responsibilities",
//   "Overthinking",
//   "Holding grudges",
//   "Procrastinating exercise",
//   "Mindless scrolling on social media",
//   "Seeking validation from others",
//   "Ignoring advice",
//   "Oversharing personal information",
//   "Overworking",
//   "Overcommitting",
//   "Staying up late",
//   "Binge-watching TV",
//   "Poor posture",
//   "Overusing electronic devices",
//   "Hoarding",
//   "Nagging",
//   "Overindulging in junk food",
//   "Blaming others",
//   "Being pessimistic",
//   "Ignoring health warnings",
//   "Ignoring personal boundaries",
//   "Complaining excessively",
//   "Being overly critical of others",
//   "Ignoring feedback",
//   "Avoiding conflict resolution",
//   "Being passive-aggressive",
//   "Ignoring warning signs",
//   "Avoiding eye contact",
//   "Avoiding self-reflection",
//   "Dwelling on the past",
//   "Avoiding social interactions",
//   "Engaging in gossip",
//   "Being ungrateful",
//   "Being self-centered",
//   "Being overly competitive",
//   "Bottling up emotions",
//   "Being defensive",
//   "Hoarding clutter",
//   "Ignoring safety precautions",
//   "Interrupting conversations",
//   "Ignoring personal hygiene",
//   "Overcommitting to social events",
//   "Neglecting responsibilities",
//   "Being unreliable",
//   "Being selfish",
//   "Being passive",
//   "Ignoring personal growth opportunities",
//   "Being disrespectful",
//   "Habitual swearing",
//   "Frequent complaining",
//   "Ignoring warnings",
//   "Being habitually late",
//   "Ignoring environmental impact",
//   "Engaging in self-sabotage",
//   "Being dismissive of others' feelings",
//   "Being dishonest",
//   "Engaging in self-destructive behaviors",
//   "Being a chronic procrastinator",
//   "Frequent oversleeping",
//   "Avoiding exercise",
//   "Overindulging in alcohol",
//   "Being confrontational",
//   "Being forgetful",
//   "Engaging in self-pity",
//   "Being manipulative",
//   "Engaging in risky behaviors",
//   "Being a chronic worrier",
//   "Ignoring personal boundaries",
//   "Engaging in self-criticism"
// ];

// const hobbies_var = [
//   "Reading",
//   "Drawing",
//   "Writing",
//   "Photography",
//   "Cooking",
//   "Hiking",
//   "Gardening",
//   "Playing musical instruments",
//   "Sports",
//   "Painting",
//   "Fishing",
//   "Cycling",
//   "Knitting",
//   "Woodworking",
//   "Yoga",
//   "Dancing",
//   "Sculpting",
//   "Calligraphy",
//   "Baking",
//   "Traveling",
//   "Swimming",
//   "Running",
//   "Singing",
//   "Birdwatching",
//   "DIY projects",
//   "Camping",
//   "Playing board games",
//   "Watching movies",
//   "Collecting stamps",
//   "Playing video games",
//   "Metal detecting",
//   "Pottery",
//   "Playing chess",
//   "Model building",
//   "Skydiving",
//   "Skiing",
//   "Surfing",
//   "Rock climbing",
//   "Meditation",
//   "Astrophotography",
//   "Tennis",
//   "Golfing",
//   "Scuba diving",
//   "Exploring caves",
//   "Kayaking",
//   "Horseback riding",
//   "Gaming",
//   "Magic tricks",
//   "Writing poetry",
//   "Making jewelry",
//   "Amateur astronomy",
//   "Archery",
//   "Reading comics",
//   "Collecting coins",
//   "Antiquing",
//   "Listening to music",
//   "Trekking",
//   "Stargazing",
//   "Martial arts",
//   "Geocaching",
//   "Playing card games",
//   "Volunteering",
//   "Chess",
//   "Stand-up comedy",
//   "Learning languages",
//   "Beekeeping",
//   "Quilting",
//   "Embroidery",
//   "Metalworking",
//   "Surfing",
//   "Windsurfing",
//   "Rowing",
//   "Sailing",
//   "Paragliding",
//   "Bungee jumping",
//   "Parkour",
//   "Ziplining",
//   "Shooting",
//   "Foraging",
//   "Bonsai",
//   "Puzzles",
//   "Fossil hunting",
//   "Horse riding",
//   "Cooking",
//   "Hiking",
//   "Gardening",
//   "Playing musical instruments",
//   "Sports",
//   "Painting",
//   "Fishing",
//   "Cycling",
//   "Knitting",
//   "Woodworking",
//   "Yoga",
//   "Dancing",
//   "Sculpting",
//   "Calligraphy",
//   "Baking",
//   "Traveling"
// ];

// const goals_var = [
//   "Publish a book",
//   "Start a business",
//   "Travel the world",
//   "Learn a new language",
//   "Solve a mystery",
//   "Save a life",
//   "Achieve a personal milestone",
//   "Overcome a fear",
//   "Build a strong relationship",
//   "Make a positive impact on society",
//   "Run a marathon",
//   "Buy a house",
//   "Earn a degree",
//   "Get promoted",
//   "Learn an instrument",
//   "Write a screenplay",
//   "Start a family",
//   "Volunteer regularly",
//   "Master a skill",
//   "Pay off debt",
//   "Adopt a pet",
//   "Start a blog",
//   "Become financially independent",
//   "Learn to cook",
//   "Become fluent in a language",
//   "Conquer a phobia",
//   "Become a mentor",
//   "Travel to every continent",
//   "Learn to code",
//   "Lose weight",
//   "Learn to dance",
//   "Get organized",
//   "Run a successful fundraiser",
//   "Become a homeowner",
//   "Quit a bad habit",
//   "Complete a triathlon",
//   "Write a novel",
//   "Learn to meditate",
//   "Become a better listener",
//   "Learn to play a sport",
//   "Get out of debt",
//   "Start a non-profit",
//   "Run a successful business",
//   "Learn to garden",
//   "Get in shape",
//   "Find inner peace",
//   "Learn to paint",
//   "Make new friends",
//   "Become a better communicator",
//   "Run for public office",
//   "Learn to swim",
//   "Develop a healthy routine",
//   "Build a professional network",
//   "Start investing",
//   "Learn to code",
//   "Travel solo",
//   "Become financially literate",
//   "Learn survival skills",
//   "Take up a new hobby",
//   "Get a promotion",
//   "Earn a certification",
//   "Start a family",
//   "Find a mentor",
//   "Become a public speaker",
//   "Learn to play an instrument",
//   "Read more books",
//   "Contribute to a cause",
//   "Learn to cook",
//   "Get involved in community service",
//   "Become a better leader",
//   "Start a business",
//   "Learn a martial art",
//   "Learn woodworking",
//   "Write a song",
//   "Travel to a specific destination",
//   "Start a YouTube channel",
//   "Take up photography",
//   "Run a successful event",
//   "Buy a car",
//   "Go on a road trip",
//   "Start a podcast",
//   "Learn to sew",
//   "Learn to play chess",
//   "Volunteer abroad",
//   "Get a degree",
//   "Learn sign language",
//   "Become an expert in a field",
//   "Learn to sculpt",
//   "Start a fitness routine",
//   "Take up gardening",
//   "Learn to fly a plane",
//   "Improve mental health",
//   "Start a side hustle",
//   "Learn about investing",
//   "Learn about personal finance",
//   "Become more organized",
//   "Learn about nutrition",
//   "Start a meditation practice"
// ];

// const favoriteFoods_var = [
//   "Pizza",
//   "Sushi",
//   "Chocolate",
//   "Tacos",
//   "Pasta",
//   "Burgers",
//   "Ice cream",
//   "Steak",
//   "Salad",
//   "Fruit",
//   "Curry",
//   "Ramen",
//   "Lasagna",
//   "Cupcakes",
//   "Donuts",
//   "Pho",
//   "Fried chicken",
//   "Cheesecake",
//   "Fish and chips",
//   "Pad Thai",
//   "Tiramisu",
//   "Enchiladas",
//   "Cinnamon rolls",
//   "Mashed potatoes",
//   "Shawarma",
//   "BBQ ribs",
//   "Gyoza",
//   "Biryani",
//   "Hamburger",
//   "Sushi rolls",
//   "Pancakes",
//   "Muffins",
//   "Chicken tikka masala",
//   "Croissants",
//   "Nachos",
//   "Creme brulee",
//   "French fries",
//   "Waffles",
//   "Beef stew",
//   "Churros",
//   "Garlic bread",
//   "Ravioli",
//   "Tandoori chicken",
//   "Falafel",
//   "Gelato",
//   "Spring rolls",
//   "Chili",
//   "Cobb salad",
//   "Macarons",
//   "Fajitas"
// ];

// const deepDarkSecrets_var = [
//   "Stole something as a child",
//   "Lied about something important",
//   "Broke someone's heart",
//   "Faked being sick to avoid responsibility",
//   "Had a secret relationship",
//   "Cheated on a test or exam",
//   "Betrayed a friend's trust",
//   "Harbored jealousy towards someone close",
//   "Hid a mistake at work",
//   "Snooped through someone's belongings",
//   "Failed to return borrowed items",
//   "Ignored someone in need",
//   "Pretended to like someone for personal gain",
//   "Sabotaged someone else's success",
//   "Secretly judged someone unfairly",
//   "Plagiarized work",
//   "Manipulated others for personal gain",
//   "Hid an addiction",
//   "Falsified information",
//   "Dishonored a promise",
//   "Borrowed money without intention to repay",
//   "Destroyed someone's property",
//   "Blamed someone else for own mistake",
//   "Gossiped maliciously",
//   "Pretended to be someone else online",
//   "Secretly envied someone's success",
//   "Used someone's personal information against them",
//   "Sabotaged a romantic relationship",
//   "Spied on someone's private conversations",
//   "Lied about personal achievements",
//   "Sabotaged a colleague's work",
//   "Manipulated others' opinions",
//   "Broke a law",
//   "Betrayed family trust",
//   "Stole credit for someone else's work",
//   "Cheated in a relationship",
//   "Ignored a cry for help",
//   "Broke a friendship without explanation",
//   "Lied to a loved one about feelings",
//   "Betrayed a professional obligation",
//   "Plotted against a colleague",
//   "Intentionally caused harm to someone",
//   "Secretly resented someone's success",
//   "Falsified evidence",
//   "Cheated in a game or competition",
//   "Ignored ethical responsibilities",
//   "Harbored resentment towards a loved one"
// ];


// // occupations, goodHabits, badHabits, hobbies, 
// // goals, favoriteFoods, deepDarkSecrets
// db.serialize(() => {
//   // Create table for occupations
//   db.run(`CREATE TABLE IF NOT EXISTS occupations (
//   id INTEGER PRIMARY KEY,
//   occupation TEXT
//   )`);

//   // Create table for good habits
//   db.run(`CREATE TABLE IF NOT EXISTS good_habits (
//       id INTEGER PRIMARY KEY,
//       good_habit TEXT
//   )`);

//   // Create table for bad habits
//   db.run(`CREATE TABLE IF NOT EXISTS bad_habits (
//       id INTEGER PRIMARY KEY,
//       bad_habit TEXT
//   )`);

//   // Create table for hobbies
//   db.run(`CREATE TABLE IF NOT EXISTS hobbies (
//       id INTEGER PRIMARY KEY,
//       hobbie TEXT
//   )`);

//   // Create table for goals
//   db.run(`CREATE TABLE IF NOT EXISTS goals (
//       id INTEGER PRIMARY KEY,
//       goal TEXT
//   )`);

//   // Create table for favorite foods
//   db.run(`CREATE TABLE IF NOT EXISTS favorite_foods (
//       id INTEGER PRIMARY KEY,
//       Favorite_food TEXT
//   )`);

//   // Create table for deep dark secrets
//   db.run(`CREATE TABLE IF NOT EXISTS deep_dark_secrets (
//       id INTEGER PRIMARY KEY,
//       deep_dark_secret TEXT
//   )`);

//   // Insert data into tables
//   const insertData = (tableName, data) => {
//     const stmt = db.prepare(`INSERT INTO ${tableName} (id, ${tableName.slice(0, -1)}) VALUES (?, ?)`);
//     data.forEach((item, index) => {
//         stmt.run(index + 1, item);
//     });
//     stmt.finalize();
//   };

//   insertData('occupations', occupations_var);
//   insertData('good_habits', goodHabits_var);
//   insertData('bad_habits', badHabits_var);
//   insertData('hobbies', hobbies_var);
//   insertData('goals', goals_var);
//   insertData('favorite_foods', favoriteFoods_var);
//   insertData('deep_dark_secrets', deepDarkSecrets_var);
//   });
  
//   // Close the database connection
//   db.close((err) => {
//       if (err) {
//           console.error(err.message);
//       }
//       console.log('Database connection closed.');

// });


